### ISSUE TITLE
custom eQTL track

### ISSUE THREAD

**Issue by fossilfriend** [NIAGADS/niagads-igv-webapp#32]
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [ ] #42

**Comment by fossilfriend** [comment]
@fossilfriend assigned #33

**Comment by simoncole** [comment]
Added parseGeneInfo function to DecodeBedXY which accomplishes adding gene ID and gene symbol to feature. Feature is then assigned the extractPopupData method which is called from the IGV code and iterates over the values in the info object and displays them while also formatting the fields to be in a more human readable form.
